apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummpy-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/liamlabuschagne/gitops-playground
    targetRevision: HEAD
    path: apps/dummpy-app
  destination:
    server: https://kubernetes.default.svc
    namespace: dummpy-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true