name: Update Deployment Image

on:
  registry_package:
    types: [published]

# create a variable mapping between package names and folders
env:
  PACKAGE_TO_FOLDER_MAP: |
    gitops-dummy-app: apps/dummy-app
    nginx: apps/nginx

jobs:
  create-commit:
    runs-on: ubuntu-latest
    # Grant necessary permissions to read packages
    permissions:
      packages: read
      contents: write
    steps:
      - name: Verify package source
        run: |
          echo "Package published: ${{ github.event.registry_package.name }}"
          echo "Version: ${{ github.event.registry_package.package_version.version }}"
          # Output the folder path based on the package name
          FOLDER_PATH=$(echo "${{ env.PACKAGE_TO_FOLDER_MAP }}" | grep "^${{ github.event.registry_package.name }}:" | cut -d':' -f2)
          if [ -z "$FOLDER_PATH" ]; then
            echo "No folder mapping found for package: ${{ github.event.registry_package.name }}"
            exit 1
          fi
          echo "FOLDER_PATH=$FOLDER_PATH" >> $GITHUB_ENV

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup git bot config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update deployment image
        env:
          FOLDER_PATH: ${{ env.FOLDER_PATH }}
        working-directory: gitops-playground
        run: |
          # Update the deployment image in the corresponding folder
          DEPLOYMENT_FILE="$FOLDER_PATH/deployment.yaml"
          if [ -f "$DEPLOYMENT_FILE" ]; then
            # Extract the new image from the published package event
            NEW_IMAGE="ghcr.io/liamlabuschagne/${{ github.event.registry_package.name }}@sha256:${{ github.event.registry_package.package_version.digest }}"
            echo "Updating deployment image to: $NEW_IMAGE"
            
            # Use yq to update the image in the deployment.yaml file
            yq eval ".spec.template.spec.containers[0].image = \"$NEW_IMAGE\"" -i "$DEPLOYMENT_FILE"
          else
            echo "Deployment file not found at: $DEPLOYMENT_FILE"
            exit 1
          fi

      - name: Commit and push
        working-directory: gitops-playground
        run: |
          git add .
          git commit -m "chore: update ${{ github.event.registry_package.name }} deployment image"
          git push
